// src/types/chat.ts

export interface ChatMessageReference {
  documentId: string; // ID of the referenced document (e.g., contract ID, project ID)
  collection: string; // Firestore collection name of the referenced document
  displayText: string; // User-friendly text for the reference (e.g., "Contract XYZ", "Project Alpha")
  pdfUrl?: string; // Storage path for PDF files, if applicable
  pageNumber?: number; // Page number if the reference is to a specific page in a PDF
  // Consider adding chunkIdentifier if you have specific text snippets to highlight
}

export interface ChatMessageInterface {
  id: string; // Unique ID for the message (e.g., generated by nanoid or a timestamp)
  text: string; // The textual content of the message
  sender: 'user' | 'llm'; // Indicates if the message is from the user or the LLM
  references?: ChatMessageReference[]; // Optional array of references for LLM messages
  timestamp: number; // Timestamp (e.g., Date.now()) for ordering messages
  // Optional: Add any other relevant fields, like error state for a message if it failed to send, etc.
}

// Optional: You might also want a type for the user object if you pass it around
// For example, if you get it from an AuthContext to pass organizationId to the backend
export interface ChatAuthUser {
  uid: string;
  organizationId?: string;
  // any other relevant user details
}
